### ISSUE TITLE
how to drop a pin instead of a polygon?

### ISSUE THREAD

**Issue by dchadney** [enam/neighborhoods#3]
First of all what you have built here is fantastic! I was just wondering if there is a way of adding a point instead of drawing an area on the map?

can I just add it here?
var sql2 ='{"type":"MultiPolygon","coordinates","Point":[[[';

**Comment by enam** [comment]
@dchadney, I'm sure that would work, but you would also need to update how leaflet.draw is called to draw a point rather than a polygon. On line 88 of hoodscipt.js the layer is called as a new L.Draw.polygon. you would want to check out the Leaflet.Draw docs and work on calling a point type instead. https://github.com/Leaflet/Leaflet.draw
I customized the leaflet.draw code for this project (not my best idea) but maybe you could pull in the clean .draw for your project and add points instead of polys.

**Comment by dchadney** [comment]
Great, thanks. I will give it a try.
